package dev.mikoto2000.rei.vectorstore;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.SearchRequest;

class SparseRetrievalTest {
  @Test void failedBaselineIsNotRetriedAsProviderFailure(){var backend=mock(RetrievalCandidates.class);when(backend.bm25Search(any())).thenThrow(new IllegalStateException("baseline unavailable"));var mismatched=new SparseRetrieval.Index(){public String modelId(){return "other";}public int dimensions(){return 100;}public List<Document> search(SearchRequest request,SparseEncoder.Vector vector){throw new AssertionError();}};assertThrows(IllegalStateException.class,()->new SparseRetrieval(backend,encoder(),mismatched).search(request()));verify(backend,times(1)).bm25Search(any());}
  SearchRequest request(){return SearchRequest.builder().query("artifact ownership").topK(2).build();}
  SparseEncoder encoder(){return new SparseEncoder(){public String modelId(){return "fixture-v1";}public SparseEncoder.Vector encode(String text,Runnable active){active.run();return new SparseEncoder.Vector("fixture-v1",100,Map.of(2,1.0,8,.25));}};}
  SparseRetrieval.Index index(){return new SparseRetrieval.Index(){public String modelId(){return "fixture-v1";}public int dimensions(){return 100;}public List<Document> search(SearchRequest request,SparseEncoder.Vector vector){assertEquals(2,request.getTopK());assertEquals(.25,vector.weights().get(8));return List.of(Document.builder().id("sparse").text("bounded result").build());}};}
  @Test void absentProviderUsesExistingBm25WithoutDenseOrEncoderCalls(){var backend=mock(RetrievalCandidates.class);when(backend.bm25Search(any())).thenReturn(List.of(Document.builder().id("baseline").text("BM25").build()));var result=new SparseRetrieval(backend,null,null).search(request());assertEquals("BM25",result.mode());assertEquals("SPARSE_NOT_CONFIGURED",result.reason());assertEquals("baseline",result.documents().getFirst().getId());verify(backend).bm25Search(any());verifyNoMoreInteractions(backend);}
  @Test void optionalProviderReturnsBoundedSparseEvidenceWithoutChangingFallback(){var backend=mock(RetrievalCandidates.class);var result=new SparseRetrieval(backend,encoder(),index()).search(request());assertEquals("LEARNED_SPARSE",result.mode());assertEquals("fixture-v1",result.modelId());assertEquals("sparse",result.documents().getFirst().getId());assertFalse(result.truthVerified());verifyNoInteractions(backend);}
  @Test void invalidVectorsModelMismatchAndUnavailableProviderFallBack(){assertThrows(IllegalArgumentException.class,()->new SparseEncoder.Vector("fixture",10,Map.of(10,1.0)));assertThrows(IllegalArgumentException.class,()->new SparseEncoder.Vector("fixture",10,Map.of(1,Double.NaN)));assertThrows(IllegalArgumentException.class,()->new SparseEncoder.Vector("fixture",10,Map.of(1,-1.0)));
    var backend=mock(RetrievalCandidates.class);when(backend.bm25Search(any())).thenReturn(List.of());var unavailable=new SparseEncoder(){public String modelId(){return "wrong-model";}public SparseEncoder.Vector encode(String text,Runnable check){throw new IllegalStateException("private provider detail");}};var result=new SparseRetrieval(backend,unavailable,index()).search(request());assertEquals("BM25",result.mode());assertFalse(result.reason().contains("private"));
  }
  @Test void filtersCannotBeBypassedByUnsupportedIndex(){var backend=mock(RetrievalCandidates.class);when(backend.bm25Search(any())).thenReturn(List.of());var filtered=SearchRequest.builder().query("artifact").topK(2).filterExpression(new org.springframework.ai.vectorstore.filter.FilterExpressionBuilder().eq("project","allowed").build()).build();var result=new SparseRetrieval(backend,encoder(),index()).search(filtered);assertEquals("SPARSE_FILTER_UNSUPPORTED",result.reason());verify(backend).bm25Search(filtered);}
  @Test void cancellationAndBudgetExhaustionNeverBecomeBm25Fallback(){var backend=mock(RetrievalCandidates.class);for(RuntimeException failure:List.of(new java.util.concurrent.CancellationException(),new dev.mikoto2000.rei.core.stagnation.ExecutionStoppedException(dev.mikoto2000.rei.core.stagnation.ExecutionStoppedException.Reason.LLM_CALL_BUDGET_EXCEEDED))){var encoder=new SparseEncoder(){public String modelId(){return "fixture-v1";}public SparseEncoder.Vector encode(String text,Runnable check){throw failure;}};assertThrows(failure.getClass(),()->new SparseRetrieval(backend,encoder,index()).search(request()));}verifyNoInteractions(backend);}
  @Test void deadlineAndInvalidIndexResultsHaveExplicitBm25Fallback(){var backend=mock(RetrievalCandidates.class);when(backend.bm25Search(any())).thenReturn(List.of());var nanos=new java.util.concurrent.atomic.AtomicLong();var slow=new SparseEncoder(){public String modelId(){return "fixture-v1";}public SparseEncoder.Vector encode(String text,Runnable active){nanos.set(1000001);active.run();return null;}};assertEquals("SPARSE_TIMEOUT",new SparseRetrieval(backend,slow,index(),nanos::get,java.time.Duration.ofMillis(1)).search(request()).reason());}
}
