package dev.mikoto2000.rei.externalagent;

import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import dev.mikoto2000.rei.core.*;
import dev.mikoto2000.rei.core.chat.AgentRunContext;
import dev.mikoto2000.rei.paper.*;
import dev.mikoto2000.rei.attention.*;

/** Explicit opt-in only. Default/full profiles exclude this entire class. */
@Tag("live")
@Timeout(value=180,unit=java.util.concurrent.TimeUnit.SECONDS)
class LiveEnvironmentE2ETest {
  @TempDir Path temporary;
  Path fixture()throws Exception{var root=Files.createDirectory(temporary.resolve("project"));Files.writeString(root.resolve("A.txt"),"before\n");return root;}
  ExternalAgentExecutor executor(ExternalAgentRequest.Agent agent,boolean persisted){if(agent==ExternalAgentRequest.Agent.CODEX){var config=new CodexProperties();config.setPersistSessions(persisted);config.setTotalTimeout(Duration.ofSeconds(60));config.setInactivityTimeout(Duration.ofSeconds(30));config.setMaxOutputBytes(1048576);return new CodexExternalAgentExecutor(config,new ExternalAgentProcessRunner());}var config=new ClaudeCodeProperties();config.setEnabled(true);config.setPersistSessions(persisted);config.setFixProposalsEnabled(true);config.setNativeSessionDirectory(temporary.resolve("private-native-sessions"));config.setTotalTimeout(Duration.ofSeconds(60));config.setInactivityTimeout(Duration.ofSeconds(30));return new ClaudeCodeExternalAgentExecutor(config,new ClaudeCodeProcessRunner());}
  dev.mikoto2000.rei.llm.ModelCallBudget budget(){return new dev.mikoto2000.rei.llm.ModelCallBudget(){int calls;public boolean tokenLimitEnabled(){return false;}public void recordTotalTokens(Integer tokens){}public void run(){if(++calls>2)throw new IllegalStateException("Live fixture call budget exceeded");}};}
  ExternalAgentRequest request(ExternalAgentRequest.Agent agent,ExternalAgentRequest.Action action,Path root,String task,String session){return new ExternalAgentRequest(agent,action,task,root,root.resolve("A.txt"),"Anonymous fixture; never access other projects",UUID.randomUUID().toString(),UUID.randomUUID().toString(),session);}
  void review(ExternalAgentRequest.Agent agent,boolean resume)throws Exception{LiveE2EPolicy.account(agent.name());var root=fixture();var adapter=executor(agent,resume);var budget=budget();var result=adapter.execute(request(agent,ExternalAgentRequest.Action.REVIEW,root,"Review the provided A.txt snapshot. Report its observed content; do not edit files.",null),()->Thread.currentThread().isInterrupted(),budget);LiveE2EPolicy.success(result);assertFalse(result.summary().isBlank());assertEquals("before\n",Files.readString(root.resolve("A.txt")));if(resume){assertNotNull(result.externalSessionId(),"Native session must be confirmed");var next=adapter.execute(request(agent,ExternalAgentRequest.Action.REVIEW,root,"Continue the same review and confirm the observed A.txt content.",result.externalSessionId()),()->Thread.currentThread().isInterrupted(),budget);LiveE2EPolicy.success(next);assertEquals(result.externalSessionId(),next.externalSessionId());assertEquals("before\n",Files.readString(root.resolve("A.txt")));}}
  @Test void codexReview()throws Exception{review(ExternalAgentRequest.Agent.CODEX,false);}
  @Test void codexResume()throws Exception{review(ExternalAgentRequest.Agent.CODEX,true);}
  @Test void claudeReview()throws Exception{review(ExternalAgentRequest.Agent.CLAUDE,false);}
  @Test void claudeResume()throws Exception{review(ExternalAgentRequest.Agent.CLAUDE,true);}
  @Test void codexImplementationDelegation()throws Exception{
    LiveE2EPolicy.account("CODEX");var root=fixture();git(root,"init","--quiet");git(root,"config","core.autocrlf","false");git(root,"config","user.name","Live Fixture");git(root,"config","user.email","live@example.invalid");git(root,"add","--","A.txt");git(root,"commit","--quiet","--no-gpg-sign","-m","anonymous fixture");
    var owner=new AgentRunContext("live-implementation","live",root,UUID.randomUUID().toString());var service=new IsolatedImplementationService(temporary.resolve("private-implementation"),new ExternalAgentProcessRunner(),new SelfPatchReviewService(new dev.mikoto2000.rei.core.service.SystemShellService()));var adapter=executor(ExternalAgentRequest.Agent.CODEX,false);var budget=budget();
    String recipe=System.getProperty("os.name").startsWith("Windows")?"git diff --check; if ($LASTEXITCODE -ne 0) { exit 1 }; if ([IO.File]::ReadAllText((Join-Path $PWD 'A.txt')) -ne \"after`n\") { exit 1 }":"git diff --check && test \"$(cat A.txt)\" = after";
    var receipt=service.implement(owner,"A.txt",recipe,10,()->Thread.currentThread().isInterrupted(),(tree,manifest)->{var result=adapter.execute(request(ExternalAgentRequest.Agent.CODEX,ExternalAgentRequest.Action.IMPLEMENT,tree,"Propose exactly one edit: change A.txt from before newline to after newline. Use the provided SHA256 baseline. Do not write files.",null),()->Thread.currentThread().isInterrupted(),budget);LiveE2EPolicy.success(result);assertNotNull(result.implementation());return result.implementation();});
    assertEquals("READY_FOR_APPROVAL",receipt.status());assertEquals("before\n",Files.readString(root.resolve("A.txt")));assertTrue(service.preview(owner,receipt.id()).diff().contains("+after"));assertEquals("MERGED",service.merge(owner,receipt.id(),receipt.patchHash(),"/agent codex merge "+receipt.id()+" "+receipt.patchHash()).status());assertEquals("after\n",Files.readString(root.resolve("A.txt")));
  }
  @Test void claudeChangeSet()throws Exception{LiveE2EPolicy.account("CLAUDE");var root=fixture();var result=executor(ExternalAgentRequest.Agent.CLAUDE,false).execute(request(ExternalAgentRequest.Agent.CLAUDE,ExternalAgentRequest.Action.PROPOSE_FIX,root,"Propose exactly A.txt: expectedText before newline, replacement after newline. Do not write files.",null),()->Thread.currentThread().isInterrupted(),budget());LiveE2EPolicy.success(result);assertNotNull(result.proposedChange());assertEquals("before\n",Files.readString(root.resolve("A.txt")));var changes=new TextChangeSetService(new TextChangeSetRepository(new org.springframework.jdbc.datasource.DriverManagerDataSource("jdbc:sqlite:"+temporary.resolve("changes.db"))));var project=new dev.mikoto2000.rei.core.project.ProjectContext(UUID.randomUUID().toString(),"anonymous",root);var proposal=changes.propose(project,result.proposedChange());assertEquals("APPLIED",changes.apply(project,proposal.id(),proposal.proposalSha256(),(path,before,after)->Files.writeString(path,after)).status());assertEquals("after\n",Files.readString(root.resolve("A.txt")));}
  @Test void paperLiveProvider(){LiveE2EPolicy.require("REI_E2E_PAPER");var config=new PaperProperties();config.setRetries(0);config.setTimeout(Duration.ofSeconds(10));var papers=new CrossrefSearchProvider(new SafePaperHttpClient(config),config).search(new PaperSearchQuery("Attention Is All You Need",2017,2017,List.of(),List.of(),false,PaperSearchQuery.Sort.RELEVANCE,3),PaperOperation.local("live-anonymous"));assertFalse(papers.isEmpty());assertTrue(papers.stream().allMatch(paper->paper.title()!=null&&!paper.title().isBlank()));}
  @Test void notificationProvider()throws Exception{LiveE2EPolicy.require("REI_E2E_NOTIFICATION");String token=System.getenv("REI_E2E_SLACK_BOT_TOKEN"),channel=System.getenv("REI_E2E_SLACK_CHANNEL");Assumptions.assumeTrue(token!=null&&!token.isBlank()&&channel!=null&&!channel.isBlank(),"SLACK_CREDENTIAL_OR_CHANNEL_MISSING");var provider=new SlackNotificationProvider(new SlackNotificationProperties(true,null,token,channel,Set.of(channel)));var id=UUID.randomUUID().toString();var outbox=new AttentionDeliveryRepository(new org.springframework.jdbc.datasource.DriverManagerDataSource("jdbc:sqlite:"+temporary.resolve("notification.db")),Clock.systemUTC());String metadata=new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(Map.of("schemaVersion",1,"id",id,"projectId","anonymous-live-fixture","kind","RUN_COMPLETED","createdAt",Instant.now().toString()));outbox.enqueue(new AttentionRepository.Item(id,"anonymous-live-fixture","live","live","RUN_COMPLETED","","","OPEN",Instant.now()),provider.destination(),"MANUAL",provider.name());assertTrue(outbox.claim("anonymous-live-fixture",id,provider.minimumIntervalMillis()));var claimed=outbox.find("anonymous-live-fixture",id).orElseThrow();NotificationProvider.Receipt receipt;try{receipt=provider.deliver(id,metadata);}catch(Exception failure){outbox.finish(claimed,"UNKNOWN","transport_outcome_unknown");throw failure;}outbox.finish(claimed,receipt);assertEquals(receipt.status(),outbox.find("anonymous-live-fixture",id).orElseThrow().status());assertEquals("SENT",receipt.status(),"Live notification outcome: "+receipt.status()+"/"+receipt.reason());assertFalse(receipt.providerReceipt().isBlank());}
  void git(Path root,String...args)throws Exception{var command=new ArrayList<String>(List.of("git","-c","core.hooksPath="));command.addAll(List.of(args));var process=new ProcessBuilder(command).directory(root.toFile()).redirectErrorStream(true).start();try{assertTrue(process.waitFor(10,java.util.concurrent.TimeUnit.SECONDS));assertEquals(0,process.exitValue(),"Fixture Git command failed");}finally{if(process.isAlive())process.destroyForcibly();}}
}
